# Generated by Django 4.2.1 on 2023-05-17 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название компании')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Завод'), (2, 'Дистрибьютор'), (3, 'Дилер'), (4, 'Розничная сеть'), (5, 'Индивидуальный предприниматель')], verbose_name='Вид компании')),
                ('email', models.EmailField(max_length=50, verbose_name='Электронная почта')),
                ('country', models.CharField(max_length=20, verbose_name='Страна')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house_number', models.CharField(max_length=10, verbose_name='Номер дома')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Задолженность')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.company')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('release', models.DateField(verbose_name='Дата выпуска')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='CompanyProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.company')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.products')),
            ],
        ),
    ]
